name: cctv-dev

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules  # <--- this line keeps node_modules inside container
    depends_on:
      - mongodb
    networks:
      - dev-net


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules  # <--- this line keeps node_modules inside container
    depends_on:
      - server
    networks:
      - dev-net

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27018:27017"    # 2708 for atlas, 27017 for local
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoUser
      - MONGO_INITDB_ROOT_PASSWORD=mongoPass
    networks:
      - dev-net


volumes:
  mongo-data:

networks:
  dev-net: